#!/bin/bash

# Check for the correct number of arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 file.tex"
    exit 1
fi

# Get the input file names from command-line arguments
file="$1"

# Check if the input files exist
if [ ! -f "$file" ]; then
    echo "Error: Input file $file not found."
    exit 1
fi

file_noending=$(echo "$file" | sed 's/\.tex$//')

rm "./${file_noending}.aux"
rm "./${file_noending}.out"
rm "./${file_noending}Notes.bib"
rm "./${file_noending}.blg"
